from beyondmeetings.models import ActionItem, MeetingNote, Section
from beyondmeetings.vault.note import render_note


def _note(**overrides):
    base = dict(
        title="Phase 4 — Plan",
        date="2026-07-30",
        tags=["meeting", "Acme"],
        attendees=["Jordan", "Sam"],
        executive_summary="We planned phase 4.",
        decisions=["Buy two licences."],
        action_items=[ActionItem(task="Procure licences", owner="Sam",
                                 due="2026-08-01", priority="HIGH")],
    )
    base.update(overrides)
    return MeetingNote(**base)


def test_frontmatter_lists_tags_and_attendees_as_yaml_blocks():
    out = render_note(_note())
    assert out.startswith("---\n")
    assert "tags:\n  - meeting\n  - Acme\n" in out
    assert "attendees:\n  - Jordan\n  - Sam\n" in out
    assert "date: 2026-07-30\n" in out


def test_h1_uses_the_display_title_with_em_dash():
    assert "\n# Phase 4 — Plan\n" in render_note(_note())


def test_follow_up_frontmatter_and_callout_present_when_linked():
    out = render_note(_note(follow_up_of="2026-07-29/Design QA Review"))
    assert 'follow_up_of: "[[Meetings/2026-07-29/Design QA Review]]"' in out
    assert "> [!note]- Follow-up to\n> [[Meetings/2026-07-29/Design QA Review]]" in out


def test_no_follow_up_key_when_standalone():
    out = render_note(_note())
    assert "follow_up_of" not in out
    assert "Follow-up to" not in out


def test_action_items_render_as_checkboxes_with_owner_and_due():
    out = render_note(_note())
    assert ("- [ ] **Procure licences** — **Sam** · Due: 2026-08-01" in out)


def test_decisions_render_under_their_heading():
    out = render_note(_note())
    assert "## Decisions Made\n- Buy two licences." in out


def test_empty_decisions_says_none_recorded():
    out = render_note(_note(decisions=[]))
    assert "## Decisions Made\nNone recorded." in out


def test_transcription_note_renders_as_warning_callout():
    out = render_note(_note(transcription_note="Heavy garbling around numbers."))
    assert "> [!warning]\n> **Transcription quality:** Heavy garbling" in out


def test_free_form_sections_render_after_typed_ones():
    out = render_note(_note(sections=[Section(heading="Key Discussion Points",
                                              bullets=["Costing gap."])]))
    assert "## Key Discussion Points\n- Costing gap." in out


def test_footer_credits_configured_tools():
    out = render_note(_note(), transcriber="Groq Whisper", provider="Claude")
    assert out.rstrip().endswith(
        "*Transcribed with Groq Whisper · Generated by beyondMeetings (Claude)*"
    )
