from beyondmeetings.config import Config
from beyondmeetings.models import ActionItem, MeetingNote
from beyondmeetings.pipeline import generate_notes
from beyondmeetings.vault.scaffold import scaffold_vault

PREV_NOTE = (
    "---\ntags:\n  - meeting\ndate: 2026-07-29\n---\n\n"
    "# Design QA Review\n\n## Executive Summary\nReviewed designs.\n\n---\n"
)


class StubProvider:
    def __init__(self, note):
        self.note = note
        self.prompts = []

    def analyse(self, prompt, valid_candidate_ids=None):
        self.prompts.append(prompt)
        return self.note


def _note(**overrides):
    base = dict(title="Phase 4 — Plan", date="2026-07-30",
                tags=["meeting", "Acme"],
                executive_summary="We planned.",
                one_line_summary="Licences approved",
                action_items=[ActionItem(task="Procure licences", owner="Sam",
                                         project="Acme", priority="HIGH")])
    base.update(overrides)
    return MeetingNote(**base)


def _setup(tmp_path, note):
    scaffold_vault(tmp_path)
    cfg = Config(vault_path=str(tmp_path), projects=["Acme"])
    return cfg, StubProvider(note)


def _with_previous(tmp_path, note):
    scaffold_vault(tmp_path)
    prev_dir = tmp_path / "Meetings" / "2026-07-29"
    prev_dir.mkdir(parents=True, exist_ok=True)
    (prev_dir / "Design QA Review.md").write_text(PREV_NOTE)
    return Config(vault_path=str(tmp_path)), StubProvider(note)


def test_writes_note_at_dated_path_with_bare_filename(tmp_path):
    cfg, provider = _setup(tmp_path, _note())
    generate_notes("transcript text", cfg, provider)
    assert (tmp_path / "Meetings" / "2026-07-30" / "Phase 4 - Plan.md").is_file()


def test_adds_tasks_to_the_board(tmp_path):
    cfg, provider = _setup(tmp_path, _note())
    generate_notes("transcript text", cfg, provider)
    board = (tmp_path / "Tasks" / "Task Board.md").read_text()
    assert "**==Procure licences==**" in board
    assert "> [!todo]+ Pending — 1" in board


def test_informal_meeting_adds_no_tasks(tmp_path):
    cfg, provider = _setup(tmp_path, _note(is_informal=True))
    generate_notes("transcript text", cfg, provider)
    board = (tmp_path / "Tasks" / "Task Board.md").read_text()
    assert "**==Procure licences==**" not in board
    assert "> [!todo]+ Pending — 0" in board


def test_informal_meeting_still_writes_the_note(tmp_path):
    cfg, provider = _setup(tmp_path, _note(is_informal=True))
    generate_notes("transcript text", cfg, provider)
    assert (tmp_path / "Meetings" / "2026-07-30" / "Phase 4 - Plan.md").is_file()


def test_informal_meeting_still_appears_in_home_recent(tmp_path):
    cfg, provider = _setup(tmp_path, _note(is_informal=True))
    generate_notes("transcript text", cfg, provider)
    assert "Phase 4 - Plan" in (tmp_path / "Home.md").read_text()


def test_home_counters_match_the_board(tmp_path):
    cfg, provider = _setup(tmp_path, _note())
    generate_notes("transcript text", cfg, provider)
    assert "> [!todo]+ Pending — 1" in (tmp_path / "Home.md").read_text()


def test_follow_up_writes_backlink_into_previous_note(tmp_path):
    cfg, provider = _with_previous(
        tmp_path, _note(follow_up_of="2026-07-29/Design QA Review")
    )
    generate_notes("transcript text", cfg, provider)
    prev = (tmp_path / "Meetings" / "2026-07-29" / "Design QA Review.md").read_text()
    assert "- Followed up in: [[Meetings/2026-07-30/Phase 4 - Plan]]" in prev


def test_follow_up_marker_appears_in_home(tmp_path):
    cfg, provider = _with_previous(
        tmp_path, _note(follow_up_of="2026-07-29/Design QA Review")
    )
    generate_notes("transcript text", cfg, provider)
    assert "↳ follow-up to" in (tmp_path / "Home.md").read_text()


def test_candidates_are_passed_to_the_prompt(tmp_path):
    cfg, provider = _with_previous(tmp_path, _note())
    generate_notes("transcript text", cfg, provider)
    assert "2026-07-29/Design QA Review" in provider.prompts[0]


def test_returns_the_written_note_path(tmp_path):
    cfg, provider = _setup(tmp_path, _note())
    result = generate_notes("transcript text", cfg, provider)
    assert result == tmp_path / "Meetings" / "2026-07-30" / "Phase 4 - Plan.md"


def test_follow_up_to_a_missing_note_degrades_to_standalone(tmp_path):
    cfg, provider = _setup(tmp_path, _note(follow_up_of="2026-01-01/Vanished"))
    generate_notes("transcript text", cfg, provider)
    assert "follow-up to" not in (tmp_path / "Home.md").read_text()


def test_footer_uses_human_readable_tool_names(tmp_path):
    cfg, provider = _setup(tmp_path, _note())
    path = generate_notes("transcript text", cfg, provider)
    text = path.read_text()
    assert "*Transcribed with Groq Whisper · Generated by beyondMeetings (Claude)*" in text
    assert "groq" not in text.split("---")[-1]
    assert "anthropic" not in text


def test_task_board_keeps_done_section_after_first_insert(tmp_path):
    cfg, provider = _setup(tmp_path, _note())
    generate_notes("transcript text", cfg, provider)
    board = (tmp_path / "Tasks" / "Task Board.md").read_text()
    assert "> [!success]- Done — 0" in board
    assert "> >\n\n> [!success]" in board
