"""Render a MeetingNote to Obsidian markdown.

Format mirrors the notes already in the live vault: YAML block sequences in
frontmatter, an em-dash display title in the H1, typed sections under fixed
headings, then free-form sections.
"""
from __future__ import annotations

from ..models import MeetingNote, MeetingRef
from .paths import meeting_wikilink


def _yaml_list(key: str, values: list[str]) -> str:
    if not values:
        return ""
    lines = "\n".join(f"  - {v}" for v in values)
    return f"{key}:\n{lines}\n"


def _bullets(items: list[str], empty: str | None = None) -> str:
    if not items:
        return f"{empty}\n" if empty else ""
    return "\n".join(f"- {i}" for i in items) + "\n"


def render_note(
    note: MeetingNote,
    transcriber: str = "Groq Whisper",
    provider: str = "Claude",
) -> str:
    parts: list[str] = ["---\n"]
    parts.append(_yaml_list("tags", note.tags))
    parts.append(f"date: {note.date}\n")
    parts.append(_yaml_list("attendees", note.attendees))

    prev_link = None
    if note.follow_up_of:
        prev_link = meeting_wikilink(MeetingRef.from_id(note.follow_up_of))
        parts.append(f'follow_up_of: "{prev_link}"\n')
    parts.append("---\n\n")

    parts.append(f"# {note.title}\n\n")
    if prev_link:
        parts.append(f"> [!note]- Follow-up to\n> {prev_link}\n\n")
    if note.transcription_note:
        parts.append(
            f"> [!warning]\n> **Transcription quality:** {note.transcription_note}\n\n"
        )

    parts.append(f"## Executive Summary\n{note.executive_summary}\n\n")
    parts.append("## Decisions Made\n" + _bullets(note.decisions, "None recorded."))
    parts.append("\n## Action Items\n")
    if note.action_items:
        for item in note.action_items:
            line = f"- [ ] **{item.task}**"
            if item.owner:
                line += f" — **{item.owner}**"
            if item.due:
                line += f" · Due: {item.due}"
            parts.append(line + "\n")
    else:
        parts.append("None recorded.\n")

    for heading, values in (
        ("Open Questions", note.open_questions),
        ("Risks / Concerns", note.risks),
        ("Follow-ups", note.follow_ups),
    ):
        if values:
            parts.append(f"\n## {heading}\n" + _bullets(values))

    for section in note.sections:
        parts.append(f"\n## {section.heading}\n" + _bullets(section.bullets))

    parts.append(
        f"\n---\n*Transcribed with {transcriber} · "
        f"Generated by beyondMeetings ({provider})*\n"
    )
    return "".join(parts)
